version: '3'
services:
  jenkins:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins.yml:/usr/share/jenkins/ref/jenkins.yml
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
