FROM amd64/gcc:13.2 AS builder

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY Makefile .

COPY app/ app/

RUN ["make"]

FROM amd64/gcc:13.2

WORKDIR /app

COPY --from=builder /app/compiled-app compiled-app


CMD ["/app/compiled-app"]