FROM python:3.12

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY requirements.txt .

RUN ["pip", "install", "--no-cache-dir", "-r", "requirements.txt"]

RUN ["rm", "requirements.txt"]

COPY ./app/ app/

ENTRYPOINT ["python", "-m", "app" ]